[chains]
ingestor = "block_ingestor_node"

[chains.mainnet]
shard = "primary"
provider = [
    # Ethereum Based Chain
    { label = "calls", details = { type = "web3", url = "$ethereum", features = [ "archive" ] }},
    # Firehose Configuration
    { label = "firehose", details = { type = "firehose", url = "https://eth.firehose.pinax.network:443", features = ["filters"], key = "$PINAX_KEY" }},
    # Substreams Configuration
    { label = "substreams", details = { type = "substreams", url = "https://eth.substreams.pinax.network:443", key = "$PINAX_KEY" }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]

[store]
[store.primary]
connection = "postgresql://${postgres_user}:${postgres_pass}@${postgres_host}:5432/${postgres_db}"
pool_size = 10