// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub data: ::prost::alloc::vec::Vec<ContractCreation>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContractCreation {
    /// block
    #[prost(string, tag="1")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub block_date: ::prost::alloc::string::String,
    /// contract creation
    #[prost(string, tag="5")]
    pub contract_address: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub creator_address: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub creator_factory: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub creator_tx: ::prost::alloc::string::String,
    /// string init = 10;
    #[prost(string, optional, tag="9")]
    pub code: ::core::option::Option<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)
