// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvmContractCreations {
    #[prost(message, repeated, tag="1")]
    pub data: ::prost::alloc::vec::Vec<ContractCreationInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContractCreationInfo {
    #[prost(string, tag="1")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(uint64, tag="3")]
    pub block_timestamp_seconds: u64,
    #[prost(string, tag="4")]
    pub contract_address: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub creator_address: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub creator_factory: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub creator_tx: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="8")]
    pub contract_init_bytecode: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub contract_bytecode: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
